### ISSUE TITLE
Can't use it on jsfiddle

### ISSUE THREAD

**Issue by allampatu** [Julien-Amblard/pixel#1]
Hello,

I was wonder why I can't use it on jsfiddle to do my tests/demo.

I haven't any kind of console error but it doesn't work.

**Comment by julien-amblard-old** [comment]
Hello, 
can i have an example ? it work fine for me

Regards

**Comment by julien-amblard-old** [comment]
May be it's a poblem with the path of the pictures. (cross-domain problem)
try with base64 img

**Comment by allampatu** [comment]
You're right. Better avoid cross-domain permalink for images.

Thanks.
